### ISSUE TITLE
Feat.req. Fix cyrillic non readable symbols in Win10 edition selection menu

### ISSUE THREAD

**Issue by necros2k7** [shadesofdeath/ShadesToolkit#1]
@shadesofdeath 
![3121212](https://github.com/shadesofdeath/ShadesToolkit/assets/16452453/0d0fd452-58ce-42c0-9310-9ef0f64e67a0)

**Comment by shadesofdeath** [comment]
First of all, thank you for reporting this issue. I will suggest a correction, please test it and provide feedback. Open the .bat file with a program like Notepad++ and add the "**chcp 65001**" code to your .bat file on the line you see in the image, which is line number 2146. Then, try again 
![Ekran Alıntısı](https://github.com/shadesofdeath/ShadesToolkit/assets/61064047/b38c75db-e6cd-447b-afdb-bcf4e91673e5)
